### ISSUE TITLE
Iteration1-DB_Forms-MVP-submission

### ISSUE THREAD

**Issue by danach707** [danielhaffuta/Reshit-Project#11]
General:
  - [x] Establish connection with DB.
  - [x] Create all relevant DB tables.
  - [x] Create HTML pages for each table.
     - [x] Add new teacher.
     - [x] Add new course.
     - [x] Set bell system.
     - [x] Set classes and grades.
     - [x] Set schedule.
     - [x] Add new student.
  - [x] Design HTML pages according to wireframes planning.

Related Issues/Tasks
  - [x] DB Infrastructure
  - [x] [iteration1 wiki page](https://github.com/danielhaffuta/Reshit-Project/wiki/Iteration1-DB_Forms-MVP)

**Comment by robi-y** [comment]
- git tag each iteration 
- nice user tests
- reference class materials!
