### ISSUE TITLE
SMS-System

### ISSUE THREAD

**Issue by danach707** [danielhaffuta/Reshit-Project#12]
## Related Issues/Tasks
 [Iteration4](https://github.com/danielhaffuta/Reshit-Project/issues/24)
#### General:
- [x] Integrate with an existing system.
- [x] Collect answers from parents and apdate child status in the group.

**Comment by idandvd** [comment]
code review: enter user name and password for the SMS system to the preferences table and not to the code.

**Comment by danielhaffuta** [comment]
SMS system done
