### ISSUE TITLE
course, student and bell system forms

### ISSUE THREAD

**Issue by morHalfon** [danielhaffuta/Reshit-Project#16]
#### General 
- [x] Add new student.
- [x] Add new course/group.
- [x] Set bell system
   
#### Related Issues/Tasks
- [ ] [iteration 1](https://github.com/danielhaffuta/Reshit-Project/issues/11)

#### Scenario 
- [ ] Enter to one of the forms
- [ ] Fill the necessary details. 
- [ ] The information will be filled in the DB

**Comment by danach707** [comment]
Code review passed
