### ISSUE TITLE
Princpal_Page

### ISSUE THREAD

**Issue by morHalfon** [danielhaffuta/Reshit-Project#18]
#### General
- [x] build principal page:
     - [x] validate that the user is defined as principal.
     - [x] give access to all the classes in the selected year
     - [x] give access to all the forms

#### Related Issues/Tasks
- [x] [iteration 2 submission](https://github.com/danielhaffuta/Reshit-Project/issues/15)

**Comment by danach707** [comment]
please review commit number 6e5cc1b5454d5123d942335a52c604b5b1f7d29f
