### ISSUE TITLE
Check Team Project 2 Submission

### ISSUE THREAD

**Issue by danielhaffuta** [danielhaffuta/Reshit-Project#2]
<h3>Project task 2:</h3>

- [x] Open group repository
- [x]  Meet up with the representor of Reshit elementry school (we will meet next week)
- [x]  Write README File specified for the team project
- [x]  Open User Manual page in wiki
- [x]  Open Product page in wiki
- [x]  Open Team page in wiki
- [x]  Open Inception page in wiki
- [x]  Collaborate repository with Eran and Reuven

**Comment by robi-y** [comment]
Nice work! a few comments:
- suggesting to mark above completed sub-tasks
- Readme: update the project description via repo. settings (it still say "A template repository with wiki for a team project at JCE's software engineering course")
    - Main project goal is vague and not focused
- Team: variance formula maybe fits robots...
- Inception: risks are very general, diagram: what is animation inflater?  

Please add me to your project, so I could change issue status
