### ISSUE TITLE
Educator_Page

### ISSUE THREAD

**Issue by morHalfon** [danielhaffuta/Reshit-Project#20]
#### General
- [x] build educator page:
  - [x] build class schedule.
  - [x] show all the students in the class.
  - [x] set a student page with details and personal schedule.

#### Related Issues/Tasks
- [ ] [iteration 3](https://github.com/danielhaffuta/Reshit-Project/issues/21)
- [ ] [user story 3](https://github.com/danielhaffuta/Reshit-Project/issues/8)

**Comment by morHalfon** [comment]
code review done
need to add to the teacher schedule - in which class he's teaching

**Comment by idandvd** [comment]
adding the class in which the teacher is teaching to the schedule.
