### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by morHalfon** [danielhaffuta/Reshit-Project#23]
this issue is for the results of the project's testing.
for each test write a scenario like this:
#### Scenario (test)
- [ ] Step 1
- [ ] ...
- [ ] Expected result

or write what you tested and how and what was the results.

**Comment by robi-y** [comment]
@danach707 @lotembenatar any update with this issue?

**Comment by danach707** [comment]
Tests have been made and bugs will be open soon.
