### ISSUE TITLE
deleting buttons

### ISSUE THREAD

**Issue by morHalfon** [danielhaffuta/Reshit-Project#33]
#### General:
- [x] add to each file a deleting button to delete information from the data base.
- [ ] ask for confirmation before deletion.
- [x] delete the chosen information only from the current school year data.

#### Related Issues/Tasks
[iteration 4](https://github.com/danielhaffuta/Reshit-Project/issues/24)

**Comment by idandvd** [comment]
code review: add confirmation option before deleting

**Comment by morHalfon** [comment]
i added a confirmation function before each deletion.
