### ISSUE TITLE
Iteration0-ZFR-Submission

### ISSUE THREAD

**Issue by danach707** [danielhaffuta/Reshit-Project#5]
- [x] Iteration page: [here](https://github.com/danielhaffuta/Reshit-Project/wiki/Iteration0-ZFR)

- [x] General:
  - [x] Create issues for all project use cases.
  - [x] Assign each issue to an iteration milestone.
  - [x] Plan Iteration 1 following the instruction gave in the course.

- [x] User Manual:
  - [x] How To Use Reshit Scheduler.
  - [x] Create a Login page.
  - [x] Permissions instructions.
  - [x] Administrator control panel instructions.

- [x] ZFR Document (Wiki page):
  - [x] Create the document following the instructions gave in the course content.
  - [x] Initiate version control system.
  - [x] Initiate a Kanban board for the project to manage the the iterations tasks.

- [x] Next iteration:
  - [x] Open page
  - [x] Select stories and plan issues

**Comment by robi-y** [comment]
- More fine grained issued for the tasks of iteration 1, so you can assign to different team members
Very nice work
